### PR TITLE
Try catch JSON.parse error

### PR DESCRIPTION
**Pull request by davidyen1124**
It causes error when doing `JSON.parse`, so I try-catch it.
I also check `responseData` and `responseData.results` is in the response.

### CODE REVIEW

**Comment by vdemedes** [comment]
Oh my, did not even think this module is still working and being used :D Thanks for PR!

**Comment by davidyen1124** [comment]
Thank you!

**Comment by vdemedes** [comment]
Published on npm as `google-images@0.1.1`.

**Comment by davidyen1124** [comment]
I use your library in my project
https://github.com/davidyen1124/Trello-Meme

Searching lots of meme pictures as Trello card cover :sunglasses:

**Comment by ballchen** [comment]
nice job :smile:

**Pull request merged**
