### PR TITLE
Refactor to work with Google Custom Search Engine

### PR DESCRIPTION
**Pull request by bravokiloecho**
As discussed in issue #10 the original API no longer works. In light of suggestions from @cpradio, I've refactored the code and the Readme so that the module now works with Google Custom Search Engine.

### CODE REVIEW

**Comment by CorWatts** [comment]
+1

**Comment by vdemedes** [comment]
This is super cool! I'll try it out this weekend. I have some thoughts regarding source code and I'll need to write tests, but considering the awesome work you've done, I will do that myself after merging ;)

Thank you!

**Comment by vdemedes** [comment]
@bravokiloecho @cpradio @CorWatts Hey guys, the rewrite of this library is in master branch. Would love if you give it a try before public release.

**Comment by CorWatts** [comment]
@vdemedes Thanks! I'll check it out this weekend.

**Comment by bravokiloecho** [comment]
@vdemedes Nice! Thanks so much for helping with this. I'm currently away on holiday but will check it as soon as I'm back to work!

**Comment by vdemedes** [comment]
@bravokiloecho No, thank **you**! This change wouldn't have happened without your contribution :) Have a great holiday!

**Comment by vdemedes** [comment]
@CorWatts Cool, let me know!

**Comment by CorWatts** [comment]
Using it very simply in an app I'm building -- it's working perfectly!

Thank you! I'll let you know if I encounter any issues...but so far so good :)

**Comment by vdemedes** [comment]
Ok great, release coming now ;)

**Comment by vdemedes** [comment]
Released on npm as `google-images@1.0.0` 🎉

**Comment by CorWatts** [comment]
YEE-YEAH :beers:

**Comment by CorWatts** [comment]
Just installed the official npm package. Looks beautiful.

**Comment by bravokiloecho** [comment]
Hello again, apologies it's taken me so long to get back to you here...

I've just installed the new module and setup it as per the Readme but I can't see to get it to produce any results. In short, the `.search` call is running but the response in the `.then' is not being triggered.

I've had a look through the code in the `index.js` file (which looks super neat) but can't figure out the path it should be following. Is there any advice you could give to help me debug what's happening?

Thanks!

**Comment by vdemedes** [comment]
Hey, try adding a .catch() block after .then() and see if the error comes up. It should definitely either resolve or reject.

**Pull request merged**
