### PR TITLE
add snippet & contextLink

### PR DESCRIPTION
**Pull request by MunifTanjim**

### CODE REVIEW

**Comment by vadimdemedes** [comment]
What are those props for?

**Comment by MunifTanjim** [comment]
`snippet` is a small description of the image.

`contextLink` is the parent page of that image.

**Comment by vadimdemedes** [comment]
Could you rename those props then? `snippet` => `description`, `contextLink` => `parentPage`. Or if you have better alternatives, happy to use those too!

**Comment by MunifTanjim** [comment]
@vadimdemedes I've made the changes

**Comment by vadimdemedes** [comment]
Thanks! Published `2.1.0`.

**Pull request merged**
