### PR TITLE
Add imgsz option, enrich package.json and readme

### PR DESCRIPTION
**Pull request by mkazantsev**
1. Added imgsz option - it's quite usefule sometimes, and I've set default value as 'medium' (for details see https://developers.google.com/image-search/v1/jsondevguide#request_format)
2. ~~Added homepage, repository (that's going to ease the pain for people who end up on npmjs.org with just a few examples and no links to source) and incremented version in package.json~~
3. ~~Added a link to API docs at Google website.~~

Hope this is helpful and my commits are not in any way offensive to your project.

Thanks!

### CODE REVIEW

**Comment by mkazantsev** [comment]
So, no `imgsz` for this lib?

**Comment by vdemedes** [comment]
Wow, did not expect a reply. Could you narrow this PR only to imgsz and possibly page?

**Comment by mkazantsev** [comment]
:smile: Sure thing, will do.

**Comment by mkazantsev** [comment]
Done. Now it just adds `imgsz` param to the query string.

**Comment by vdemedes** [comment]
Thanks!

**Pull request merged**
